### ISSUE TITLE
Please upgrade to 0.10

### ISSUE THREAD

**Issue by fesse** [graingert/slimerjs#46]
The version downloaded by this module is 0.9.6 while the most recent public version at slimerjs.org is 0.10 
Please upgrade to the latest version.

**Comment by graingert** [comment]
0.10.0 will not be supported by this repo. If you want 0.10.0 on npm see laurentj/slimerjs#489

**Comment by KevinGrandon** [comment]
> 0.10.0 will not be supported by this repo. If you want 0.10.0 on npm see laurentj/slimerjs#489

@graingert - Thanks for all of your work on this repo over the years, it has been very valuable to a lot of people including myself. 

Could you provide some reasoning as to why you won't support slimer 0.10? Even if the slimer core project supported it, it would be very useful for a project to provide slimer and firefox in a single NPM install, and I'm not sure if the core project will provide the Firefox download as well.

**Comment by graingert** [comment]
I'm not putting Firefox on npm :p

**Comment by KevinGrandon** [comment]
I agree with that, but we could download it from Mozilla servers and have the npm package install it.

E.g., to get the latest firefox: https://download.mozilla.org/?product=firefox-latest&os=win&lang=en-US

**Comment by graingert** [comment]
The reason I don't want to support 0.10 is because it's a platform
independent set of scripts. It should be included directly in npm and be
maintained upstream

On 26 Jul 2016 00:05, "Kevin Grandon" <notifications@github.com> wrote:

I agree with that, but we could download it from Mozilla servers and have
the npm package install it.

E.g., to get the latest firefox:
https://download.mozilla.org/?product=firefox-latest&os=win&lang=en-US

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/graingert/slimerjs/issues/46#issuecomment-235113311>,
or mute the thread
